/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AITaggerPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian2 = require("obsidian");

// rate-limiter.ts
var RateLimiter = class {
  constructor(config) {
    this.requests = [];
    this.windowMs = 6e4;
    this.maxRequests = config.requestsPerMinute;
  }
  updateConfig(config) {
    this.maxRequests = config.requestsPerMinute;
  }
  async waitIfNeeded() {
    const now = Date.now();
    this.requests = this.requests.filter(
      (timestamp) => now - timestamp < this.windowMs
    );
    if (this.requests.length >= this.maxRequests) {
      const oldestRequest = Math.min(...this.requests);
      const waitTime = this.windowMs - (now - oldestRequest) + 100;
      if (waitTime > 0) {
        await new Promise((resolve) => setTimeout(resolve, waitTime));
        return this.waitIfNeeded();
      }
    }
    this.requests.push(now);
  }
  getRemainingRequests() {
    const now = Date.now();
    this.requests = this.requests.filter(
      (timestamp) => now - timestamp < this.windowMs
    );
    return Math.max(0, this.maxRequests - this.requests.length);
  }
  getTimeUntilReset() {
    if (this.requests.length === 0) return 0;
    const now = Date.now();
    const oldestRequest = Math.min(...this.requests);
    return Math.max(0, this.windowMs - (now - oldestRequest));
  }
};

// i18n.ts
var translations = {
  en: {
    // Plugin general
    "plugin.name": "AI Tagger",
    "plugin.description": "Automatically generate relevant tags for your notes using AI",
    // Commands
    "command.generateTags": "Generate tags for current note",
    "command.generateTagsAll": "Generate tags for all notes",
    // Ribbon
    "ribbon.generateTags": "Generate AI Tags",
    // Notices
    "notice.noActiveFile": "No active file",
    "notice.notMarkdown": "Active file is not a markdown file",
    "notice.generatingTags": "Generating tags...",
    "notice.noTagsGenerated": "No tags generated",
    "notice.noNewTags": "No new tags to add",
    "notice.tagsAdded": "Added {count} tags: {tags}",
    "notice.errorGenerating": "Error generating tags: {error}",
    "notice.batchComplete": "Batch processing complete. Processed: {processed}, Errors: {errors}",
    "notice.processingFiles": "Processing {count} files...",
    "notice.processedFiles": "Processed {processed}/{total} files...",
    "notice.rateLimitHit": "Rate limit reached. Waiting {seconds} seconds...",
    "notice.retryingRequest": "Request failed, retrying ({attempt}/{maxAttempts})...",
    // Settings
    "settings.title": "AI Tagger Settings",
    "settings.language": "Language",
    "settings.language.desc": "Choose interface language",
    "settings.defaultProvider": "Default AI Provider",
    "settings.defaultProvider.desc": "Choose between OpenAI (ChatGPT) or Claude",
    "settings.openaiKey": "OpenAI API Key",
    "settings.openaiKey.desc": "Your OpenAI API key",
    "settings.claudeKey": "Claude API Key",
    "settings.claudeKey.desc": "Your Anthropic Claude API key",
    "settings.minTags": "Minimum Tags",
    "settings.minTags.desc": "Minimum number of tags to generate",
    "settings.maxTags": "Maximum Tags",
    "settings.maxTags.desc": "Maximum number of tags to generate",
    "settings.customPrompt": "Custom Prompt",
    "settings.customPrompt.desc": "Custom prompt to use for tag generation",
    "settings.autoApply": "Auto Apply Tags",
    "settings.autoApply.desc": "Automatically apply generated tags without preview",
    "settings.excludeExisting": "Exclude Existing Tags",
    "settings.excludeExisting.desc": "Do not generate tags that already exist in the note",
    "settings.rateLimit": "Rate Limit (requests/minute)",
    "settings.rateLimit.desc": "Maximum API requests per minute",
    "settings.maxRetries": "Max Retries",
    "settings.maxRetries.desc": "Maximum retry attempts for failed API calls",
    // Modals
    "modal.tagPreview.title": "Generated Tags Preview",
    "modal.tagPreview.file": "File: {filename}",
    "modal.tagPreview.apply": "Apply Selected Tags",
    "modal.tagPreview.cancel": "Cancel",
    "modal.batchProcessing.title": "Batch Processing",
    "modal.batchProcessing.description": "This will generate tags for all markdown files in your vault.",
    "modal.batchProcessing.warning": "\u26A0\uFE0F This may take a while and consume API credits. Are you sure?",
    "modal.batchProcessing.proceed": "Proceed",
    "modal.batchProcessing.cancel": "Cancel",
    // Errors
    "error.openaiKeyMissing": "OpenAI API key not configured",
    "error.claudeKeyMissing": "Claude API key not configured",
    "error.openaiApi": "OpenAI API error: {status}",
    "error.claudeApi": "Claude API error: {status}",
    "error.openaiError": "OpenAI error: {message}",
    "error.claudeError": "Claude error: {message}",
    "error.maxRetriesReached": "Maximum retry attempts reached",
    "error.rateLimitExceeded": "Rate limit exceeded"
  },
  fr: {
    // Plugin général
    "plugin.name": "AI Tagger",
    "plugin.description": "G\xE9n\xE8re automatiquement des tags pertinents pour vos notes avec l'IA",
    // Commandes
    "command.generateTags": "G\xE9n\xE9rer des tags pour la note actuelle",
    "command.generateTagsAll": "G\xE9n\xE9rer des tags pour toutes les notes",
    // Ruban
    "ribbon.generateTags": "G\xE9n\xE9rer des Tags IA",
    // Notifications
    "notice.noActiveFile": "Aucun fichier actif",
    "notice.notMarkdown": "Le fichier actif n'est pas un fichier markdown",
    "notice.generatingTags": "G\xE9n\xE9ration des tags...",
    "notice.noTagsGenerated": "Aucun tag g\xE9n\xE9r\xE9",
    "notice.noNewTags": "Aucun nouveau tag \xE0 ajouter",
    "notice.tagsAdded": "{count} tags ajout\xE9s : {tags}",
    "notice.errorGenerating": "Erreur lors de la g\xE9n\xE9ration des tags : {error}",
    "notice.batchComplete": "Traitement par lot termin\xE9. Trait\xE9s : {processed}, Erreurs : {errors}",
    "notice.processingFiles": "Traitement de {count} fichiers...",
    "notice.processedFiles": "Trait\xE9s {processed}/{total} fichiers...",
    "notice.rateLimitHit": "Limite de d\xE9bit atteinte. Attente de {seconds} secondes...",
    "notice.retryingRequest": "\xC9chec de la requ\xEAte, nouvelle tentative ({attempt}/{maxAttempts})...",
    // Paramètres
    "settings.title": "Param\xE8tres AI Tagger",
    "settings.language": "Langue",
    "settings.language.desc": "Choisir la langue de l'interface",
    "settings.defaultProvider": "Fournisseur IA par d\xE9faut",
    "settings.defaultProvider.desc": "Choisir entre OpenAI (ChatGPT) ou Claude",
    "settings.openaiKey": "Cl\xE9 API OpenAI",
    "settings.openaiKey.desc": "Votre cl\xE9 API OpenAI",
    "settings.claudeKey": "Cl\xE9 API Claude",
    "settings.claudeKey.desc": "Votre cl\xE9 API Anthropic Claude",
    "settings.minTags": "Tags minimum",
    "settings.minTags.desc": "Nombre minimum de tags \xE0 g\xE9n\xE9rer",
    "settings.maxTags": "Tags maximum",
    "settings.maxTags.desc": "Nombre maximum de tags \xE0 g\xE9n\xE9rer",
    "settings.customPrompt": "Prompt personnalis\xE9",
    "settings.customPrompt.desc": "Prompt personnalis\xE9 pour la g\xE9n\xE9ration de tags",
    "settings.autoApply": "Appliquer automatiquement",
    "settings.autoApply.desc": "Appliquer automatiquement les tags g\xE9n\xE9r\xE9s sans aper\xE7u",
    "settings.excludeExisting": "Exclure les tags existants",
    "settings.excludeExisting.desc": "Ne pas g\xE9n\xE9rer les tags qui existent d\xE9j\xE0 dans la note",
    "settings.rateLimit": "Limite de d\xE9bit (requ\xEAtes/minute)",
    "settings.rateLimit.desc": "Nombre maximum de requ\xEAtes API par minute",
    "settings.maxRetries": "Tentatives maximum",
    "settings.maxRetries.desc": "Nombre maximum de tentatives pour les appels API \xE9chou\xE9s",
    // Modales
    "modal.tagPreview.title": "Aper\xE7u des tags g\xE9n\xE9r\xE9s",
    "modal.tagPreview.file": "Fichier : {filename}",
    "modal.tagPreview.apply": "Appliquer les tags s\xE9lectionn\xE9s",
    "modal.tagPreview.cancel": "Annuler",
    "modal.batchProcessing.title": "Traitement par lot",
    "modal.batchProcessing.description": "Ceci g\xE9n\xE8rera des tags pour tous les fichiers markdown de votre coffre.",
    "modal.batchProcessing.warning": "\u26A0\uFE0F Cela peut prendre du temps et consommer des cr\xE9dits API. \xCAtes-vous s\xFBr ?",
    "modal.batchProcessing.proceed": "Continuer",
    "modal.batchProcessing.cancel": "Annuler",
    // Erreurs
    "error.openaiKeyMissing": "Cl\xE9 API OpenAI non configur\xE9e",
    "error.claudeKeyMissing": "Cl\xE9 API Claude non configur\xE9e",
    "error.openaiApi": "Erreur API OpenAI : {status}",
    "error.claudeApi": "Erreur API Claude : {status}",
    "error.openaiError": "Erreur OpenAI : {message}",
    "error.claudeError": "Erreur Claude : {message}",
    "error.maxRetriesReached": "Nombre maximum de tentatives atteint",
    "error.rateLimitExceeded": "Limite de d\xE9bit d\xE9pass\xE9e"
  }
};
var I18n = class {
  constructor(language = "en") {
    this.currentLanguage = "en";
    this.currentLanguage = language;
  }
  setLanguage(language) {
    this.currentLanguage = language;
  }
  getCurrentLanguage() {
    return this.currentLanguage;
  }
  t(key, params) {
    const translation = translations[this.currentLanguage][key] || translations.en[key] || key;
    if (!params) {
      return translation;
    }
    return translation.replace(/\{(\w+)\}/g, (match, paramKey) => {
      var _a;
      return ((_a = params[paramKey]) == null ? void 0 : _a.toString()) || match;
    });
  }
};
var i18n = new I18n();

// ai-service.ts
var import_obsidian = require("obsidian");
var AIService = class {
  constructor(settings) {
    this.settings = settings;
    this.rateLimiter = new RateLimiter({ requestsPerMinute: settings.rateLimit });
  }
  updateSettings(settings) {
    this.settings = settings;
    this.rateLimiter.updateConfig({ requestsPerMinute: settings.rateLimit });
  }
  async generateTags(content) {
    await this.rateLimiter.waitIfNeeded();
    if (this.settings.defaultProvider === "openai") {
      return this.generateTagsWithRetry(content, "openai");
    } else {
      return this.generateTagsWithRetry(content, "claude");
    }
  }
  async generateTagsWithRetry(content, provider) {
    let lastError = "";
    for (let attempt = 1; attempt <= this.settings.maxRetries; attempt++) {
      try {
        if (attempt > 1) {
          new import_obsidian.Notice(i18n.t("notice.retryingRequest", {
            attempt: attempt.toString(),
            maxAttempts: this.settings.maxRetries.toString()
          }));
          const delay = Math.pow(2, attempt - 1) * 1e3;
          await new Promise((resolve) => setTimeout(resolve, delay));
        }
        if (provider === "openai") {
          return await this.generateTagsWithOpenAI(content);
        } else {
          return await this.generateTagsWithClaude(content);
        }
      } catch (error) {
        lastError = error.message;
        if (error.message.includes("401") || error.message.includes("403")) {
          return { tags: [], error: lastError };
        }
        if (error.message.includes("429")) {
          return { tags: [], error: i18n.t("error.rateLimitExceeded") };
        }
      }
    }
    return { tags: [], error: i18n.t("error.maxRetriesReached") + ": " + lastError };
  }
  async generateTagsWithOpenAI(content) {
    if (!this.settings.openaiApiKey) {
      return { tags: [], error: i18n.t("error.openaiKeyMissing") };
    }
    try {
      const response = await fetch("https://api.openai.com/v1/chat/completions", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "Authorization": `Bearer ${this.settings.openaiApiKey}`
        },
        body: JSON.stringify({
          model: "gpt-3.5-turbo",
          messages: [
            {
              role: "system",
              content: `${this.settings.customPrompt} Generate between ${this.settings.minTags} and ${this.settings.maxTags} tags. Return only the tags as a comma-separated list, no other text.`
            },
            {
              role: "user",
              content: content.substring(0, 4e3)
            }
          ],
          max_tokens: 100,
          temperature: 0.3
        })
      });
      if (!response.ok) {
        throw new Error(i18n.t("error.openaiApi", { status: response.status.toString() }));
      }
      const data = await response.json();
      const tagsText = data.choices[0].message.content.trim();
      const tags = this.parseTags(tagsText);
      return { tags };
    } catch (error) {
      throw new Error(i18n.t("error.openaiError", { message: error.message }));
    }
  }
  async generateTagsWithClaude(content) {
    if (!this.settings.claudeApiKey) {
      return { tags: [], error: i18n.t("error.claudeKeyMissing") };
    }
    try {
      const response = await fetch("https://api.anthropic.com/v1/messages", {
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          "x-api-key": this.settings.claudeApiKey,
          "anthropic-version": "2023-06-01"
        },
        body: JSON.stringify({
          model: "claude-3-haiku-20240307",
          max_tokens: 100,
          messages: [
            {
              role: "user",
              content: `${this.settings.customPrompt} Generate between ${this.settings.minTags} and ${this.settings.maxTags} tags for this content. Return only the tags as a comma-separated list, no other text.

Content: ${content.substring(0, 4e3)}`
            }
          ]
        })
      });
      if (!response.ok) {
        throw new Error(i18n.t("error.claudeApi", { status: response.status.toString() }));
      }
      const data = await response.json();
      const tagsText = data.content[0].text.trim();
      const tags = this.parseTags(tagsText);
      return { tags };
    } catch (error) {
      throw new Error(i18n.t("error.claudeError", { message: error.message }));
    }
  }
  parseTags(tagsText) {
    return tagsText.split(",").map((tag) => tag.trim().toLowerCase()).filter((tag) => tag.length > 0 && tag.length <= 50).slice(0, this.settings.maxTags);
  }
};

// settings.ts
var DEFAULT_SETTINGS = {
  openaiApiKey: "",
  claudeApiKey: "",
  defaultProvider: "openai",
  maxTags: 5,
  minTags: 2,
  customPrompt: "Generate relevant tags for this note content. Focus on main topics, themes, and categories. Return tags as a comma-separated list. Each tag will not contain spaces, but dashes.",
  batchProcessing: false,
  autoApplyTags: false,
  excludeExistingTags: true,
  language: "en",
  rateLimit: 10,
  maxRetries: 3
};

// main.ts
var AITaggerPlugin = class extends import_obsidian2.Plugin {
  async onload() {
    await this.loadSettings();
    i18n.setLanguage(this.settings.language);
    this.aiService = new AIService(this.settings);
    this.addRibbonIcon("tag", i18n.t("ribbon.generateTags"), () => {
      this.generateTagsForActiveFile();
    });
    this.addCommand({
      id: "generate-tags-current-note",
      name: i18n.t("command.generateTags"),
      callback: () => {
        this.generateTagsForActiveFile();
      }
    });
    this.addCommand({
      id: "generate-tags-all-notes",
      name: i18n.t("command.generateTagsAll"),
      callback: () => {
        this.showBatchProcessingModal();
      }
    });
    this.addSettingTab(new AITaggerSettingTab(this.app, this));
  }
  async generateTagsForActiveFile() {
    const activeFile = this.app.workspace.getActiveFile();
    if (!activeFile) {
      new import_obsidian2.Notice(i18n.t("notice.noActiveFile"));
      return;
    }
    if (activeFile.extension !== "md") {
      new import_obsidian2.Notice(i18n.t("notice.notMarkdown"));
      return;
    }
    await this.generateTagsForFile(activeFile);
  }
  async generateTagsForFile(file) {
    const notice = new import_obsidian2.Notice(i18n.t("notice.generatingTags"), 0);
    try {
      const content = await this.app.vault.read(file);
      const contentWithoutFrontmatter = this.removeYamlFrontmatter(content);
      const response = await this.aiService.generateTags(contentWithoutFrontmatter);
      if (response.error) {
        notice.hide();
        new import_obsidian2.Notice(i18n.t("notice.errorGenerating", { error: response.error }));
        return;
      }
      if (response.tags.length === 0) {
        notice.hide();
        new import_obsidian2.Notice(i18n.t("notice.noTagsGenerated"));
        return;
      }
      const existingTags = this.extractExistingTags(content);
      let newTags = response.tags;
      if (this.settings.excludeExistingTags) {
        newTags = response.tags.filter((tag) => !existingTags.includes(tag));
      }
      if (newTags.length === 0) {
        notice.hide();
        new import_obsidian2.Notice(i18n.t("notice.noNewTags"));
        return;
      }
      if (this.settings.autoApplyTags) {
        await this.applyTagsToFile(file, newTags);
        notice.hide();
        new import_obsidian2.Notice(i18n.t("notice.tagsAdded", { count: newTags.length.toString(), tags: newTags.join(", ") }));
      } else {
        notice.hide();
        this.showTagPreviewModal(file, newTags);
      }
    } catch (error) {
      notice.hide();
      new import_obsidian2.Notice(i18n.t("notice.errorGenerating", { error: error.message }));
    }
  }
  removeYamlFrontmatter(content) {
    const frontmatterRegex = /^---\s*\n.*?\n---\s*\n/s;
    return content.replace(frontmatterRegex, "");
  }
  extractExistingTags(content) {
    const frontmatterMatch = content.match(/^---\s*\n(.*?)\n---\s*\n/s);
    if (!frontmatterMatch) return [];
    const frontmatter = frontmatterMatch[1];
    const tagsMatch = frontmatter.match(/tags:\s*\[(.*?)\]/s) || frontmatter.match(/tags:\s*\n((?:\s*-\s*.+\n?)*)/);
    if (!tagsMatch) return [];
    if (tagsMatch[1].includes("[")) {
      return tagsMatch[1].split(",").map((tag) => tag.trim().replace(/['"]/g, ""));
    } else {
      return tagsMatch[1].split("\n").map((line) => line.trim().replace(/^-\s*/, "").replace(/['"]/g, "")).filter((tag) => tag.length > 0);
    }
  }
  async applyTagsToFile(file, tags) {
    const content = await this.app.vault.read(file);
    const newContent = this.addTagsToContent(content, tags);
    await this.app.vault.modify(file, newContent);
  }
  addTagsToContent(content, tags) {
    const frontmatterMatch = content.match(/^---\s*\n(.*?)\n---\s*\n/s);
    if (frontmatterMatch) {
      const frontmatter = frontmatterMatch[1];
      const existingTags = this.extractExistingTags(content);
      const allTags = [.../* @__PURE__ */ new Set([...existingTags, ...tags])];
      const tagsYaml = `tags: [${allTags.map((tag) => `"${tag}"`).join(", ")}]`;
      let newFrontmatter = frontmatter;
      if (frontmatter.includes("tags:")) {
        newFrontmatter = frontmatter.replace(/tags:\s*\[.*?\]/s, tagsYaml);
        newFrontmatter = newFrontmatter.replace(/tags:\s*\n((?:\s*-\s*.+\n?)*)/s, tagsYaml);
      } else {
        newFrontmatter = frontmatter + "\n" + tagsYaml;
      }
      return content.replace(frontmatterMatch[0], `---
${newFrontmatter}
---
`);
    } else {
      const tagsYaml = `tags: [${tags.map((tag) => `"${tag}"`).join(", ")}]`;
      return `---
${tagsYaml}
---

${content}`;
    }
  }
  showTagPreviewModal(file, tags) {
    new TagPreviewModal(this.app, file, tags, async (selectedTags) => {
      if (selectedTags.length > 0) {
        await this.applyTagsToFile(file, selectedTags);
        new import_obsidian2.Notice(i18n.t("notice.tagsAdded", { count: selectedTags.length.toString(), tags: selectedTags.join(", ") }));
      }
    }).open();
  }
  showBatchProcessingModal() {
    new BatchProcessingModal(this.app, this).open();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
    i18n.setLanguage(this.settings.language);
    this.aiService.updateSettings(this.settings);
  }
};
var TagPreviewModal = class extends import_obsidian2.Modal {
  constructor(app, file, tags, onSubmit) {
    super(app);
    this.file = file;
    this.tags = tags;
    this.onSubmit = onSubmit;
    this.selectedTags = new Set(tags);
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: i18n.t("modal.tagPreview.title") });
    contentEl.createEl("p", { text: i18n.t("modal.tagPreview.file", { filename: this.file.name }) });
    const tagsContainer = contentEl.createDiv({ cls: "tags-container" });
    this.tags.forEach((tag) => {
      const tagEl = tagsContainer.createDiv({ cls: "tag-item" });
      const checkbox = tagEl.createEl("input", { type: "checkbox" });
      checkbox.checked = this.selectedTags.has(tag);
      checkbox.addEventListener("change", () => {
        if (checkbox.checked) {
          this.selectedTags.add(tag);
        } else {
          this.selectedTags.delete(tag);
        }
      });
      tagEl.createSpan({ text: tag, cls: "tag-text" });
    });
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const applyButton = buttonContainer.createEl("button", { text: i18n.t("modal.tagPreview.apply") });
    applyButton.addEventListener("click", () => {
      this.onSubmit(Array.from(this.selectedTags));
      this.close();
    });
    const cancelButton = buttonContainer.createEl("button", { text: i18n.t("modal.tagPreview.cancel") });
    cancelButton.addEventListener("click", () => {
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var BatchProcessingModal = class extends import_obsidian2.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.createEl("h2", { text: i18n.t("modal.batchProcessing.title") });
    contentEl.createEl("p", { text: i18n.t("modal.batchProcessing.description") });
    const warningEl = contentEl.createEl("p", { cls: "warning" });
    warningEl.setText(i18n.t("modal.batchProcessing.warning"));
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const proceedButton = buttonContainer.createEl("button", { text: i18n.t("modal.batchProcessing.proceed") });
    proceedButton.addEventListener("click", () => {
      this.processBatch();
      this.close();
    });
    const cancelButton = buttonContainer.createEl("button", { text: i18n.t("modal.batchProcessing.cancel") });
    cancelButton.addEventListener("click", () => {
      this.close();
    });
  }
  async processBatch() {
    const files = this.app.vault.getMarkdownFiles();
    const notice = new import_obsidian2.Notice(i18n.t("notice.processingFiles", { count: files.length.toString() }), 0);
    let processed = 0;
    let errors = 0;
    for (const file of files) {
      try {
        await this.plugin.generateTagsForFile(file);
        processed++;
      } catch (error) {
        errors++;
        console.error(`Error processing ${file.name}:`, error);
      }
      if (processed % 10 === 0) {
        notice.setMessage(i18n.t("notice.processedFiles", { processed: processed.toString(), total: files.length.toString() }));
      }
    }
    notice.hide();
    new import_obsidian2.Notice(i18n.t("notice.batchComplete", { processed: processed.toString(), errors: errors.toString() }));
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};
var AITaggerSettingTab = class extends import_obsidian2.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: i18n.t("settings.title") });
    new import_obsidian2.Setting(containerEl).setName(i18n.t("settings.language")).setDesc(i18n.t("settings.language.desc")).addDropdown((dropdown) => dropdown.addOption("en", "English").addOption("fr", "Fran\xE7ais").setValue(this.plugin.settings.language).onChange(async (value) => {
      this.plugin.settings.language = value;
      await this.plugin.saveSettings();
      this.display();
    }));
    new import_obsidian2.Setting(containerEl).setName(i18n.t("settings.defaultProvider")).setDesc(i18n.t("settings.defaultProvider.desc")).addDropdown((dropdown) => dropdown.addOption("openai", "OpenAI (ChatGPT)").addOption("claude", "Claude").setValue(this.plugin.settings.defaultProvider).onChange(async (value) => {
      this.plugin.settings.defaultProvider = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName(i18n.t("settings.openaiKey")).setDesc(i18n.t("settings.openaiKey.desc")).addText((text) => text.setPlaceholder("sk-...").setValue(this.plugin.settings.openaiApiKey).onChange(async (value) => {
      this.plugin.settings.openaiApiKey = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName(i18n.t("settings.claudeKey")).setDesc(i18n.t("settings.claudeKey.desc")).addText((text) => text.setPlaceholder("sk-ant-...").setValue(this.plugin.settings.claudeApiKey).onChange(async (value) => {
      this.plugin.settings.claudeApiKey = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName(i18n.t("settings.minTags")).setDesc(i18n.t("settings.minTags.desc")).addSlider((slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.minTags).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.minTags = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName(i18n.t("settings.maxTags")).setDesc(i18n.t("settings.maxTags.desc")).addSlider((slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.maxTags).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxTags = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName(i18n.t("settings.customPrompt")).setDesc(i18n.t("settings.customPrompt.desc")).addTextArea((text) => text.setPlaceholder("Generate relevant tags...").setValue(this.plugin.settings.customPrompt).onChange(async (value) => {
      this.plugin.settings.customPrompt = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName(i18n.t("settings.autoApply")).setDesc(i18n.t("settings.autoApply.desc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.autoApplyTags).onChange(async (value) => {
      this.plugin.settings.autoApplyTags = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName(i18n.t("settings.excludeExisting")).setDesc(i18n.t("settings.excludeExisting.desc")).addToggle((toggle) => toggle.setValue(this.plugin.settings.excludeExistingTags).onChange(async (value) => {
      this.plugin.settings.excludeExistingTags = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName(i18n.t("settings.rateLimit")).setDesc(i18n.t("settings.rateLimit.desc")).addSlider((slider) => slider.setLimits(1, 60, 1).setValue(this.plugin.settings.rateLimit).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.rateLimit = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian2.Setting(containerEl).setName(i18n.t("settings.maxRetries")).setDesc(i18n.t("settings.maxRetries.desc")).addSlider((slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.maxRetries).setDynamicTooltip().onChange(async (value) => {
      this.plugin.settings.maxRetries = value;
      await this.plugin.saveSettings();
    }));
  }
};
